---
title: Foundations of Probability for Countably Infinite Sample Spaces
author: Mathematics for Computation and Data Science
date: Arnob Roy
output: pdf_document
header-includes:
  - \usepackage{titling}
  - \pretitle{\begin{flushleft}\LARGE \scshape}
  - \posttitle{\end{flushleft}}
  
  - \preauthor{\begin{flushleft}\large}
  - \postauthor{\end{flushleft}}
  
  - \predate{\begin{flushleft}\large}
  - \postdate{\end{flushleft}}
---

# R Problems
## Problem 1. The New York Mets' performance in 1962

```{r}
#Read the .csv file
Mets <- read.csv("Mets.csv"); head(Mets)

#Let's wrangle the data
data.clean <- subset(Mets, subset = (W.L == "W"|W.L == "L"|W.L == "W-wo"))

#Tally up the games
rows <- nrow(data.clean)
data.clean$tally <- rep(NA, times=rows)
counter <- 0
for (i in 1:rows){
  if (data.clean$W.L[i] == "L") {counter <- counter+1}
  else if (data.clean$W.L[i] != "L") {data.clean$tally[i]<-(counter+1); counter <- 0}
}
```

```{r}
tallies <- as.data.frame(table(data.clean$tally)); tallies

#since there are only 10 rows, I will construct the vector for the bar plot of interest by hand
barplotnames <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16)
tallies <- c(11,10,3,4,2,2,1,0,0,3,0,0,1,0,0,1)
barplot(tallies, names.arg = barplotnames, col = "blue")

#Geometric distribution with probability 1/4
barplot(dgeom(1:16, prob=0.25), names.arg = barplotnames, col = "red")
```








